name: Deploy Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'apps/documentation/**'
  workflow_dispatch:


permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  # This job checks if the 'documentation' environment exists
  get-environments:
    name: Get Environments
    runs-on: ubuntu-latest
    timeout-minutes: 1
    permissions:
      actions: read
    outputs:
      names: ${{ steps.set_env.outputs.names }}
    steps:
      - name: Get environments
        uses: octokit/request-action@b91aabaa861c777dcdb14e2387e30eddf04619ae # v3.0.0
        id: get_env
        with:
          route: GET /repos/${{ github.repository }}/environments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output
        id: set_env
        # This step filters for the 'documentation' environment from the list of environments
        run: |
          names=$(echo "$NAMES" | jq -c '[.[] | select(. == "documentation")]')
          echo "Filtered environments: $names"
          echo "names=$names" >> $GITHUB_OUTPUT
        env:
          NAMES: ${{ toJson(fromJson(steps.get_env.outputs.data).environments.*.name) }}
  check:
    name: CI
    runs-on: ubuntu-latest
    needs: get-environments
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Spell Check
        uses: streetsidesoftware/cspell-action@9cd41bb518a24fefdafd9880cbab8f0ceba04d28 # v8.3.0
        with:
          files: 'apps/documentation/**/*.md'
          incremental_files_only: false
          suggestions: true

      - name: Build
        run: pnpm run build:docs
  deploy:
    # If there are no documentation environment to deploy to, this job will be skipped
    if: ${{ needs.get-environments.outputs.names != '[]'}}
    name: Deploy Documentation
    needs: CI
    runs-on: ubuntu-latest
    environment:
      name: documentation
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Build
        run: pnpm run build:docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
